on: push
jobs:
    job_linux:
        runs-on: ubuntu-latest
        steps:
        - run: cmake --version
    job_windows:
        runs-on: windows-latest
        steps:
        - run: cmake --version