on: push
jobs:
    job_linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: cmake --version
        - run: pwd
        - run: cd test
        - run: cmake -B build
        - run: cmake --build build
        - run: cmake --build build --target run